const Menu = [
  {
    id: 1,
    name: "Tea",
    image: "images/Tea.jpg",
    category: "Breakfast",
    price: "25Rs",
    description: "nice",
  },
  {
    id: 2,
    name: "Jirarice",
    image: "images/jira.jpg",
    category: "Lunch",
    price: "25Rs",
    description: "nice",
  },
  {
    id: 3,
    name: "samosa",
    image: "images/samosa.jpg",
    category: "Breakfast",
    price: "25Rs",
    description: "nice",
  },
  {
    id: 4,
    name: "vadapau",
    image: "images/vadapau.jpg",
    category: "Breakfast",
    price: "25Rs",
    description: "nice",
  },
  {
    id: 5,
    name: "maggie",
    image: "images/maggi.jpg",
    category: "Breakfast",
    price: "25Rs",
    description: "nice",
  },
  {
    id: 6,
    name: "sevtameta",
    image: "images/sevtameta.jpg",
    category: "Dinner",
    price: "25Rs",
    description: "nice",
  },
  {
    id: 7,
    name: "iceCream",
    image: "images/iceCream.jpg",
    category: "Sweet",
    price: "25Rs",
    description: "nice",
  },
];

export default Menu;
